export const imprintAbi = [
  {
    type: "function",
    name: "mint",
    stateMutability: "payable",
    inputs: [
      { name: "xId", type: "bytes32" },
      { name: "traits", type: "bytes32" },
      { name: "handle", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "refresh",
    stateMutability: "payable",
    inputs: [
      { name: "traits", type: "bytes32" },
      { name: "handle", type: "string" },
      { name: "deadline", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "quoteMint",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteRefresh",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "MINT_USD",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "mintedToken",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isHolder",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "passport",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "traits", type: "bytes32" },
      { name: "typeName", type: "string" },
      { name: "rarityScore", type: "uint256" },
      { name: "holding", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "tokenURI",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "Minted",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "id", type: "uint256", indexed: true },
      { name: "xId", type: "bytes32", indexed: false },
      { name: "traits", type: "bytes32", indexed: false },
      { name: "handle", type: "string", indexed: false },
    ],
  },
] as const;
